CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;

GRANT CREATE SESSION TO ORCLSTUDY;

ALTER USER ORCLSTUDY IDENTIFIED BY ORCL;

DROP USER ORCLSTUDY;

DROP USER ORCLSTUDY CASCADE;

CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;

GRANT CREATE SESSION TO ORCLSTUDY;

ALTER USER ORCLSTUDY IDENTIFIED BY ORASTDY;

GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;
-- 계정에 사용자 권한 부여

ALTER USER ORCLSTUDY IDENTIFIED BY ORACLE;

CREATE ROLE ROLESTUDY;
-- 롤스터디 계정생성

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;
-- 롤스터디 계정에 CONNECT 롤과 RESOURCE 롤 뷰생성권한과 동의어생성 권한 부여

GRANT ROLESTUDY TO ORCLSTUDY;

CREATE USER PREV_HW IDENTIFIED BY ORCL;
-- 게정생성

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO PREV_HW;





